-- 1번
SELECT STUDENT_NO AS "학번" , STUDENT_NAME AS "이름", ENTRANCE_DATE AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

-- 2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)!=3;

-- 3번
SELECT PROFESSOR_NAME AS "교수이름", TO_CHAR(SYSDATE,'YYYY')-(SUBSTR(PROFESSOR_SSN,1,2)+1900) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1)=1
ORDER BY 2;

-- 4번
SELECT SUBSTR(PROFESSOR_NAME,2,3) AS "이름"
FROM TB_PROFESSOR;

-- 5번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE TO_CHAR(ENTRANCE_DATE,'yyyy') - TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN,1,6)),'YYYY')>19;

-- 6번
SELECT TO_CHAR(TO_DATE(20201225),'DY')
FROM DUAL;

-- 7번
SELECT TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD'), TO_DATE('99/10/11', 'RR/MM/DD'), TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;

-- 8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';

-- 9번
SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10번
SELECT DEPARTMENT_NO AS "학과번호", COUNT(DEPARTMENT_NO) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE NVL(COACH_PROFESSOR_NO, 'N')='N';

-- 12번
SELECT SUBSTR(TERM_NO, 1, 4), ROUND(AVG(POINT),1)
FROM TB_GRADE
GROUP BY SUBSTR(TERM_NO, 1, 4);
--HAVING STUDENT_NO = 'A112113';

-- 13번
